In [2]:
#import Libraries


import pandas as pd
import numpy as np

In [3]:
#Load Excel
df = pd.read_excel('Netflix_Unclean_Project.xlsx')

In [4]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20

In [5]:
df.tail()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [7]:
df.shape

(1013, 20)

In [10]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Title', 'Content_Type', 'Genre',
       'Country', 'Subscription_Plan', 'Device', 'Payment_Method',
       'Account_Status', 'Join_Date', 'Last_Watch_Date', 'Watch_Hours',
       'Monthly_Fee', 'Movies_Watched', 'Episodes_Watched', 'Avg_Rating',
       'Monthly_Sessions', 'Download_Count'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1013 non-null   str
 1   Customer_Name      1013 non-null   str
 2   Age                1013 non-null   int64
 3   Title              1013 non-null   str
 4   Content_Type       1013 non-null   str
 5   Genre              1010 non-null   str
 6   Country            1013 non-null   str
 7   Subscription_Plan  1013 non-null   str
 8   Device             1009 non-null   str
 9   Payment_Method     1008 non-null   str
 10  Account_Status     1013 non-null   str
 11  Join_Date          1013 non-null   datetime64[us]
 12  Last_Watch_Date    1013 non-null   datetime64[us]
 13  Watch_Hours        1013 non-null   float64
 14  Monthly_Fee        1013 non-null   int64
 15  Movies_Watched     1013 non-null   int64
 16  Episodes_Watched   1013 non-null   int64
 17  Avg_Rating         1013 non-null   float64
 18  Monthly_Sessions   1013 non-null   int64
 19  Download_Count     1013 non-null   int64
dtypes: datetime64[us](2), float64(2), int64(6), str(10)
memory usage: 158.4 KB

In [13]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1013.000000,1013,1013,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000
mean,42.063179,2023-12-16 10:21:12.260612,2024-11-27 19:59:45.784797,42.417473,436.222113,18.187562,59.834156,3.752419,16.686081,12.472853
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-08 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,31.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-29 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-13 00:00:00,2025-11-14 00:00:00,58.100000,649.000000,27.000000,91.000000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.245811,NaN,NaN,23.988529,214.348252,10.123758,34.895300,0.722812,8.290083,7.577303

In [14]:
# missing values
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [16]:
# duplicate record
df.duplicated().sum()

np.int64(5)

In [19]:
# remove duplicate value
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [20]:
# dirty values
df.replace(
    ['N/A','',' ','NULL'],np.nan,inplace=True
)

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [21]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                4
Country              1
Subscription_Plan    0
Device               4
Payment_Method       7
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [24]:
#  remove extra spaces
df =df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [26]:
#standardize text
df =df.apply(lambda x: x.str.title() if x.dtype == "object" else x)

In [28]:
df['Country'].value_counts()

Country
Spain               109
United States       107
Germany             104
Canada              103
Japan               100
United Kingdom      100
India                97
France               96
South Korea          95
Australia            91
  United Kingdom      1
SOUTH KOREA           1
  France              1
FRANCE                1
UNITED KINGDOM        1
Name: count, dtype: int64

In [30]:
# numeric columns
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Title', 'Content_Type', 'Genre',
       'Country', 'Subscription_Plan', 'Device', 'Payment_Method',
       'Account_Status', 'Join_Date', 'Last_Watch_Date', 'Watch_Hours',
       'Monthly_Fee', 'Movies_Watched', 'Episodes_Watched', 'Avg_Rating',
       'Monthly_Sessions', 'Download_Count'],
      dtype='str')

In [31]:
num_columns =['Age','Watch_Hours','Monthly_Fee','Movies_Watched'
              ,'Episodes_Watched','Avg_Rating','Monthly_Sessions','Download_Count']

In [32]:
for col in num_columns:
    df[col] =pd.to_numeric(df[col],errors='coerce')

In [34]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1008.000000,1008,1008,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000
mean,42.097222,2023-12-15 20:42:51.428571,2024-11-28 00:20:00,42.449107,435.960317,18.226190,59.766865,3.751984,16.690476,12.448413
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-07 18:00:00,2023-12-25 12:00:00,25.650000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,54.000000,2024-12-13 00:00:00,2025-11-14 06:00:00,58.100000,649.000000,27.000000,90.250000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.258334,NaN,NaN,24.016448,214.461100,10.099231,34.916046,0.724172,8.287380,7.559714

In [35]:
df =df[(df['Age']>=18)&(df['Age']<=100)]

In [36]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1003.000000,1003,1003,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000
mean,41.973081,2023-12-15 07:20:45.463609,2024-11-26 23:08:18.903290,42.391326,436.543370,18.242273,59.723829,3.751346,16.673978,12.449651
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-07 12:00:00,2023-12-25 00:00:00,25.450000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-02 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.500000,2024-12-12 00:00:00,2025-11-13 12:00:00,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,13.811906,NaN,NaN,24.016402,214.305681,10.092691,34.891084,0.723284,8.285836,7.559756

In [39]:
# negative value
df = df[df['Watch_Hours']>=0]
df =df[df['Monthly_Fee']>0]

In [43]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,995.000000,995,995,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000
mean,41.920603,2023-12-16 04:27:44.321608,2024-11-27 13:52:09.648241,42.605126,438.396985,18.217085,59.514573,3.754573,16.701508,12.460302
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,0.000000,149.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-09 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-02 00:00:00,42.300000,499.000000,18.000000,58.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-10 00:00:00,2025-11-12 00:00:00,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,13.797644,NaN,NaN,23.784772,209.136478,10.085605,34.855299,0.723983,8.280686,7.564557

In [46]:
# missing value handle
df["Age"] =df["Age"].fillna(
    df["Age"].mean()
)
df["Watch_Hours"] =df["Watch_Hours"].fillna(
    df["Watch_Hours"].mean()
)
df["Monthly_Fee"] =df["Monthly_Fee"].fillna(
    df["Monthly_Fee"].mean()
)

In [52]:
df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")

df["Device"] = df["Device"].fillna("Unknown")

df["Genre"] = df["Genre"].fillna("Unknown")

In [54]:
#feature engineering

#customer Revenue
df["Customer_Revenue"] = (df["Monthly_Fee"] * df["Monthly_Sessions"])

In [55]:
# Engagemnet Score

df["Engagement_Score"]= (df["Watch_Hours"]+df["Monthly_Sessions"]+df["Download_Count"])

In [56]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,2024-12-21,28.0,649,5,97,3.6,11,3,7139,42.0
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,2024-08-14,0.0,149,5,84,4.5,22,19,3278,41.0
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,2025-10-31,28.9,149,16,106,3.8,26,3,3874,57.9
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,2023-06-18,27.6,649,10,24,2.6,27,9,17523,63.6
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,2025-06-09,32.0,649,10,78,3.2,15,20,9735,67.0

In [57]:
# Watch Category
bins =[0,20,50,100,np.inf]
label =["Low","Medium","High","Very High"]
df["Watch_Category"] = pd.cut(df["Watch_Hours"],bins=bins,labels=label)

In [58]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,28.0,649,5,97,3.6,11,3,7139,42.0,Medium
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,0.0,149,5,84,4.5,22,19,3278,41.0,NaN
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,28.9,149,16,106,3.8,26,3,3874,57.9,Medium
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,27.6,649,10,24,2.6,27,9,17523,63.6,Medium
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,32.0,649,10,78,3.2,15,20,9735,67.0,Medium

In [59]:
# Age group 
bins =[17,25,35,50,100]
label =['18-25','26-35','36-50','51+']

df["Age_Group"]= pd.cut(df["Age"],bins=bins,labels=label)

In [60]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,649,5,97,3.6,11,3,7139,42.0,Medium,18-25
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,149,5,84,4.5,22,19,3278,41.0,NaN,36-50
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,149,16,106,3.8,26,3,3874,57.9,Medium,36-50
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,649,10,24,2.6,27,9,17523,63.6,Medium,36-50
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,649,10,78,3.2,15,20,9735,67.0,Medium,51+

In [62]:
# Account active flag
df["Active_Flag"] = np.where(df["Account_Status"] == "Active",1,0)

In [63]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group,Active_Flag
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,5,97,3.6,11,3,7139,42.0,Medium,18-25,1
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,5,84,4.5,22,19,3278,41.0,NaN,36-50,1
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,16,106,3.8,26,3,3874,57.9,Medium,36-50,0
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,Medium,36-50,1
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,10,78,3.2,15,20,9735,67.0,Medium,51+,1

In [65]:
# clean excel export
df.to_csv("Netflix_Clean_Data.csv",index=False)

In [70]:
from sqlalchemy import create_engine
engine =create_engine("mysql+pymysql://root:root@localhost/Netflix_db")

In [69]:
%pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\roaming\python\python314\site-packages (2.1.4)
Requirement already satisfied: pymysql in c:\users\dell\appdata\roaming\python\python314\site-packages (1.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\roaming\python\python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [73]:
df.to_sql(
    "Netflix_Customers",
    con = engine,
    if_exists ='replace',
index =False
)

C:\Users\DELL\AppData\Local\Temp\ipykernel_8012\4050848745.py:1: UserWarning: The provided table name 'Netflix_Customers' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(

995